Homework01
Lors3654/cs102 pull request #2
Opened 2020-10-09 17:06 UTC by Lors3654

2020-10-12 18:05 UTC, Dementiy requested changes

2020-10-12 18:05 UTC, Dementiy commented on caesar.py
> +    for i in text:
На этом месте проверка работы останавливается, так как код нерабочий, переменной `text` не существует. Также не соблюдены правила оформления работы, читайте раздел настройка рабочего окружения.

2020-10-13 16:34 UTC, Dementiy requested changes
Работа не проходит тесты - исправляйте.

2020-10-16 21:16 UTC, Dementiy requested changes
1. Ваш код не проходит тесты
2. Надо удалить pyc файлы

2020-10-18 12:59 UTC, Dementiy requested changes
1. Ваш код не проходит тесты
2. Нужно удалить pyc-файлы

2020-10-19 22:54 UTC, Dementiy requested changes
Уже в третий раз пишу, что надо удалить pyc-файлы. Находясь на ветке homework01 выполните следующие команды (так как я пишу их без проверки, то следует быть внимательным на наличие ошибок):

```
git rm -r homework01/__pycache__
git rm -r homework01/tests/__pycache__
git rm -r __pycache__
echo "__pycache__/" >> .gitignore
git commit -m "Удалены pyc-файлы и добавлены в .gitignore"
git push origin homework01
```

Также настройте github actions.

2020-10-20 17:05 UTC, Dementiy requested changes
Надо удалить pyc-файлы. Находясь на ветке homework01 выполните следующие команды (так как я пишу их без проверки, то следует быть внимательным на наличие ошибок):

```
git rm -r homework01/__pycache__
git rm -r homework01/tests/__pycache__
git rm -r __pycache__
echo "__pycache__/" >> .gitignore
git commit -m "Удалены pyc-файлы и добавлены в .gitignore"
git push origin homework01
```

Также настройте github actions и запустите black.

2020-10-21 23:24 UTC, Dementiy requested changes
Ничего не изменилось

2020-10-22 16:48 UTC, Dementiy requested changes
1. Файл cs102 почему-то пустой
2. Не соблюдены правила оформления работы
3. Есть замечания

2020-10-22 16:48 UTC, Dementiy commented on homework01/caesar.py
> +        if ord(i)>=65 and ord(i)<=90:
Программисты не любят магических чисел, поэтому им обычно дают имена или используют выражение как есть, например:

```python
if ord("A") <= ord(x) <= ord(Z")
```

В других местах аналогично.

2020-10-23 20:55 UTC, Dementiy requested changes
Еще несколько изменений.

2020-10-23 20:55 UTC, Dementiy commented on homework01/caesar.py
> +            ciphertext = chr((((ord(i) - 97) + shift) % 26) + 97)
Кажется, что вы не читаете, что я пишу в замечаниях.

Программисты не любят магических чисел, поэтому им обычно дают имена или используют выражение как есть, например:

```python
if ord("A") <= ord(x) <= ord(Z")
```

В других местах аналогично.

2020-10-23 20:59 UTC, Lors3654 commented on homework01/caesar.py
> +            ciphertext = chr((((ord(i) - 97) + shift) % 26) + 97)
но ведь я изменила код по вашим указаниям, сделала как у вас в примере

2020-10-23 22:16 UTC, Dementiy requested changes
Сборка-то не прошла:
![Screenshot 2020-10-24 at 01 16 02](https://user-images.githubusercontent.com/4396325/97058427-7eb4fc00-1596-11eb-8728-462157716479.png)

2020-10-23 22:38 UTC, Dementiy requested changes
Вот вы пишите:
![Screenshot 2020-10-24 at 01 36 44](https://user-images.githubusercontent.com/4396325/97059552-62ff2500-1599-11eb-9f71-83d0f242b103.png)

И вот, что у вас в файлах:
![Screenshot 2020-10-24 at 01 37 38](https://user-images.githubusercontent.com/4396325/97059593-80cc8a00-1599-11eb-9b30-0b0873c8a2d7.png)

Посмотрите, во всех местах вы сделали изменение?

2020-10-23 22:40 UTC, Dementiy commented on homework01/caesar.py
> +            ciphertext = chr((((ord(i) - 97) + shift) % 26) + 97)
К сожалению не совсем. Вы применили лишь частично то, на что я указал.

2020-12-18 08:03 UTC, merged