Homework03
Lors3654/cs102 pull request #4
Opened 2020-11-23 16:59 UTC by Lors3654

Для реализации клеточного поля мы будем использовать набор модулей pygame, предназначенный для создания компьютерных игр. Правила игры «Жизнь» достаточно простые:1) «Жизнь» разыгрывается на бесконечном клеточном поле. 2) У каждой клетки 8 соседних клеток. 3) В каждой клетке может жить существо. 4) Существо с двумя или тремя соседями выживает в следующем поколении, иначе погибает от одиночества или перенаселённости. 5) В пустой клетке с тремя соседями в следующем поколении рождается существо.

2020-12-04 22:03 UTC, Dementiy requested changes
1. Лишних файлов быть не должно
![Screenshot 2020-12-05 at 01 03 06](https://user-images.githubusercontent.com/4396325/101219820-a3bc8480-3695-11eb-94de-77f891d77fd6.png)
2. Графическая версия игры не запускается

2020-12-07 19:37 UTC, Dementiy requested changes
Лишних файлов в работе быть не должно:
![Screenshot 2020-12-07 at 22 36 43](https://user-images.githubusercontent.com/4396325/101396638-b07ee980-38dc-11eb-961b-7b50900b66a6.png)

2020-12-08 16:44 UTC, Dementiy requested changes
Используйте `git rm` для удаления файлов:
![Screenshot 2020-12-08 at 19 43 33](https://user-images.githubusercontent.com/4396325/101513823-a9fc7a80-398d-11eb-91fc-c2257f2929fa.png)

2020-12-08 18:50 UTC, Lors3654 commented
я так и делала. В гите этих файлов нет, откуда вы их нашли?

2020-12-08 18:52 UTC, Lors3654 commented
аааа, нашла в мастере. Наверное, и вы их там нашли. А я думала, только на ветке homework03

2020-12-11 20:58 UTC, Dementiy requested changes
Пока не решили проблему. Посмотрите чатик, я уже писал о возможных путях решения:
![Screenshot 2020-12-11 at 23 58 25](https://user-images.githubusercontent.com/4396325/101954230-c35f2a00-3c0c-11eb-9831-f922dfbf1d7c.png)

2020-12-14 20:56 UTC, Dementiy requested changes
1. Должен быть один файл cs102.yml, у вас их два.
2. Графическая версия игры не запускается.
3. Нужно избавиться от pyc-файлов, например, командой `git rm`. Если по какой-то причине эти файлы у вас в мастер ветке, то сначала их надо удалить оттуда, а затем влить изменения из мастер ветки в homework03. В чате я описывал примерную схему.

2020-12-19 21:06 UTC, Dementiy approved these changes

2020-12-19 22:48 UTC, merged